server:
  port: 9595
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: pawan
    url: jdbc:mysql://localhost:3306/nov

    username: pawan
  jpa:
      properties:
        hibernate:

      hibernate:
        ddl-auto: none

      show-sql: true